### PR TITLE
Be more noisy about errors and add an `onError` option

### LINKED ISSUE #52: Make errors more obvious
After getting no data errors this morning from Datadog, I found ```metrics ERROR: add_metrics failed: null (err=Error: certificate has expired, status=0) +324ms``` with DEBUG mode enabled.

I'd think this should fire an error, not just a debug log.

### PR DESCRIPTION
**Pull request by Mr0grog**
This fixes #52 by making two changes:

1. Add an `onError` option where users can provide an error handler for auto-flushes, just like they do when calling `flush()` explicitly. This is useful for getting more detail about the error, doing custom logging, or sending the error to a separate error tracking service, like Sentry.io.

2. In cases where the error was not handled (either via the `onError` option or by manually calling `flush()` with an error handler), this logs the error to the console *regardless* of the environment’s `DEBUG` setting. This particular error is a pretty big deal and should not be silenced.

I did the second change by making a special logging function for errors, since `debug` does not have a concept of levels or any way to temporarily override the environment (you can call `enable()`, but that overrides whatever was set before, so you can’t just put things back the way they were once you do that).

### CODE REVIEW

File: lib/reporters.js [hunk 1]
```diff
@@ -51,10 +51,7 @@ function DataDogReporter(apiKey, appKey, apiHost) {
 }
 
 DataDogReporter.prototype.report = function(series, onSuccess, onError) {
-    if (debug.enabled) {
-        // Only call stringify when debugging.
-        debug('Calling report with %s', JSON.stringify(series));
-    }
+    logDebug('Calling report with %j', series);
```
Comment (Mr0grog) [inline lib/reporters.js:54]: I noticed when changing this to `logDebug` that debug has a `%j` formatter for logging an object as JSON. Not sure if it’s new or if we just didn’t know about it before, but it makes this a little nicer and means we don’t need to wrap this in an `if` statement.

**Comment by Mr0grog** [comment]
I think both these changes make good sense, but the second one in particular is a big change in behavior — this is the first time this library will log directly to the console regardless of your `DEBUG` setting, so people might see this starting to log when it never has before (but that’s a good thing, since they would have been having errors the whole time and maybe not known it).

File: lib/logging.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+const debug = require('debug');
+
+const prefix = 'metrics';
+
+/**
+ * A prefixed instance of the `debug` logger. You can call this directly, or
+ * call `extend()` on it to create a nested logger.
+ * @type {debug.Debugger}
+ */
+const logDebug = debug(prefix);
```
Comment (Mr0grog) [inline lib/logging.js:13]: Forgot to note that I started doing JSDoc-style comments in this new module in anticipation of #86, since the TypeScript compiler can build type definitions from JSDoc comments but not from the style of comments currently used in other files.

**Review by ErikBoesen — APPROVED** [review]
Looks great!
