### PR TITLE
Fix the broken `apiHost` option

### LINKED ISSUE #42: Make the datadog endpoint configurable
The endpoint URL of datadog should be configurable (for testing and special setups).
The underlying dogapi library already supports it.

### PR DESCRIPTION
**Pull request by Mr0grog**
It looks like the `apiHost` option was added in #50, had some fixes committed directly to the main branch later (?), and then was broken in #62 when the underlying Datadog client implementation was changed. This fixes it, and resolves #42.

The `agent` option was also broken in #62, but the PR discussion makes that look intentional (while there are no notes about breaking `apiHost`). However, only part of the implementation awas removed and it was still documented in some spots. I also cleaned all that out here.

I think it might also be a good idea to *deprecate* this option name and change it to `site`, since that’s what this is called throughout Datadog’s official docs.

### CODE REVIEW

File: lib/reporters.js [hunk 1]
```diff
@@ -23,9 +23,10 @@ NullReporter.prototype.report = function(series, onSuccess) {
 // DataDogReporter
 //
 
-function DataDogReporter(apiKey, appKey) {
+function DataDogReporter(apiKey, appKey, apiHost) {
     apiKey = apiKey || process.env.DATADOG_API_KEY;
     appKey = appKey || process.env.DATADOG_APP_KEY;
+    this.apiHost = apiHost || process.env.DATADOG_API_HOST;
```
Comment (Mr0grog) [inline lib/reporters.js:29]: I made this public so it can be easily inspected, and it’s not sensitive like the API key and app key are. LMK if that’s not OK.

File: lib/reporters.js [hunk 2]
```diff
@@ -37,6 +38,15 @@ function DataDogReporter(apiKey, appKey) {
             appKeyAuth: appKey
         }
     });
+    if (this.apiHost) {
+        // Strip leading `app.` from the site in case someone copy/pasted the
+        // URL from their web browser. More details on correct configuration:
+        // https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site
+        this.apiHost = apiHost.replace(/^app\./i, '');
```
Comment (Mr0grog) [inline lib/reporters.js:45]: The previous README used `app.datadoghq.com` in the README, which does not work. I’m not sure if it used to.

I tested this with the default site and with `us3.datadoghq.com`.

**Review by ErikBoesen — APPROVED** [review]
Looks good! Thank you!
